#!/usr/bin/env python3
"""Build the documentation site in docs/ from the HTML fragments in docs/src/.

Run from the repository root: python3 docs/build_docs.py
Output: docs/index.html (English), one page per translation, and docs/webui.html.

Brand: lab-in-a-box identity (graphite, porcelain, teal, navy, coral, sand; Schibsted Grotesk + JetBrains Mono).
Diagrams: the Mermaid blocks in docs/src/ are swapped for the brand SVGs in media/diagrams/
(generated by media/generate_diagrams.mjs); any Mermaid block that is not recognised is left as is.
"""
import html
import re
import shutil
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parent
SOURCE = DOCS / "src"
MEDIA = DOCS.parent / "media"
REPO_URL = "https://github.com/SUSE-Technical-Marketing/lab-in-a-box"

PAGES = [
    ("index.html", "index.html", "English"),
    ("de.html", "de.html", "Deutsch"),
    ("es.html", "es.html", "Español"),
    ("fr.html", "fr.html", "Français"),
    ("ja.html", "ja.html", "日本語"),
    ("pt-BR.html", "pt-BR.html", "Português (Brasil)"),
    ("zh-CN.html", "zh-CN.html", "简体中文"),
    ("webui.html", "webui.html", "Web UI"),
]

# Mermaid marker (node id that never gets translated) -> [(diagram file, English alt text), ...]
DIAGRAMS = {
    "AutoVM[": [
        ("architecture", "Architecture: your client talks to the automation VM, which creates lab VMs on KVM hypervisors or other compute backends"),
        ("network", "Network and services: laptop, router and a LAN with the automation VM (DNS, HTTP) and a three-node Kubernetes cluster"),
    ],
    "phase_services": [("pipeline", "Deploy pipeline: services, DNS, create VMs, reboot and wait, install Kubernetes, VM add-ons")],
    "get_backend": [("backends", "Compute backends: get_backend() routes to libvirt, Harvester or one of eight public clouds")],
    "Hub[": [("overlay", "Cross-cloud WireGuard overlay: site gateways connect to a hub; nodes route through their own gateway")],
    "S1[": [("quickstart", "Quick start in six steps")],
    "Lab[": [("lab-format", "Lab definition format: nodes, common, kclusters and add-on sections that reference each other")],
}

IMPORT_MAP = """<script type="importmap">
{
  "imports": {
    "three": "https://unpkg.com/three@0.184.0/build/three.module.js",
    "three/addons/controls/OrbitControls.js": "https://unpkg.com/three@0.184.0/examples/jsm/controls/OrbitControls.js"
  },
  "integrity": {
    "https://unpkg.com/three@0.184.0/build/three.module.js": "sha384-8FCZ1eVO6it4+pbec2aDtnTrwjWXZLJRC+MAGCIPDgsYnUrl/E0A2YlF8ioMKI/J",
    "https://unpkg.com/three@0.184.0/build/three.core.js": "sha384-dw2ooPewaEIrAgl6oFDBmmBWCE9oW9LxRGcfwZ0hLvEprzo202wXl7vCYHRlSnOT",
    "https://unpkg.com/three@0.184.0/examples/jsm/controls/OrbitControls.js": "sha384-4rziNxOBZKQ69i+w+f89KJ55TCYquwchVbByQwmaOeIOXdOU2PLDn3kOfXHwIJC9"
  }
}
</script>"""

FONTS = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
    '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
    'family=Schibsted+Grotesk:wght@400;500;600;700;800'
    '&family=JetBrains+Mono:wght@400;500&display=swap">'
)

STYLE = """
:root {
  --bg: #eceef1; --panel: #ffffff; --ink: #23272d; --muted: #5a606b; --line: #dfe2e6;
  --accent: #12a99d; --link: #0b6e67; --on-accent: #ffffff;
  --code-bg: #23272d; --code-ink: #eceef1; --inline-code: #e3e6ea; --stage: #f6f7f8;
  --tint: #e5f3f1; --coral: #e2725b; --navy: #1f2f4a; --sand: #d9c7a3;
  --shadow: 0 1px 2px rgba(35,39,45,.06), 0 8px 24px rgba(35,39,45,.05);
  --sans: "Schibsted Grotesk", "Helvetica Neue", Helvetica, Arial, sans-serif;
  --mono: "JetBrains Mono", ui-monospace, Menlo, Consolas, monospace;
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --bg: #16191e; --panel: #23272d; --ink: #f3f4f5; --muted: #a9aeb7; --line: #353a42;
    --accent: #2fd1c2; --link: #2fd1c2; --on-accent: #16191e;
    --code-bg: #1b1e23; --code-ink: #eceef1; --inline-code: #2c3138; --stage: #1b1e23;
    --tint: #1f3a3a; --coral: #f08a74; --navy: #b5bfd0;
    --shadow: 0 1px 3px rgba(0,0,0,.35), 0 8px 26px rgba(0,0,0,.28); color-scheme: dark;
  }
}
:root[data-theme="dark"] {
  --bg: #16191e; --panel: #23272d; --ink: #f3f4f5; --muted: #a9aeb7; --line: #353a42;
  --accent: #2fd1c2; --link: #2fd1c2; --on-accent: #16191e;
  --code-bg: #1b1e23; --code-ink: #eceef1; --inline-code: #2c3138; --stage: #1b1e23;
  --tint: #1f3a3a; --coral: #f08a74; --navy: #b5bfd0;
  --shadow: 0 1px 3px rgba(0,0,0,.35), 0 8px 26px rgba(0,0,0,.28); color-scheme: dark;
}
*, *::before, *::after { box-sizing: border-box; }
html { -webkit-text-size-adjust: 100%; scroll-behavior: smooth; scroll-padding-top: 88px; }
body {
  margin: 0; background: var(--bg); color: var(--ink);
  font: 400 17px/1.65 var(--sans); -webkit-font-smoothing: antialiased;
}
a { color: var(--link); text-underline-offset: 3px; text-decoration-thickness: 1px; }
a:hover { color: var(--accent); text-decoration-thickness: 2px; }
:focus-visible { outline: 2px solid var(--accent); outline-offset: 3px; border-radius: 3px; }

/* ---- header ---- */
.topbar-wrap { position: sticky; top: 0; z-index: 20; background: color-mix(in srgb, var(--bg) 88%, transparent); backdrop-filter: blur(10px); border-bottom: 1px solid var(--line); }
.topbar {
  max-width: 1240px; margin: 0 auto; padding: 12px 24px;
  display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 10px 20px;
}
.lockup { display: block; height: 36px; width: auto; }
.lockup--dark { display: none; }
.opening-text h1 .lockup { display: inline-block; height: 3.4rem; vertical-align: middle; }
.opening-text h1 .lockup--dark { display: none; }
html[data-theme="dark"] .lockup--light { display: none !important; }
html[data-theme="dark"] .lockup--dark { display: block; }
html[data-theme="dark"] .opening-text h1 .lockup--dark { display: inline-block; }
@media (prefers-color-scheme: dark) {
  html:not([data-theme="light"]) .lockup--light { display: none !important; }
  html:not([data-theme="light"]) .lockup--dark { display: block; }
  html:not([data-theme="light"]) .opening-text h1 .lockup--dark { display: inline-block; }
}
.topbar-right { display: flex; flex-wrap: wrap; align-items: center; gap: 8px 16px; }
.topbar nav { display: flex; flex-wrap: wrap; align-items: center; gap: 2px 4px; font: 500 13px/1.4 var(--sans); }
.topbar nav a { color: var(--muted); text-decoration: none; padding: 5px 10px; border-radius: 999px; }
.topbar nav a:hover { color: var(--ink); background: var(--panel); }
.topbar nav a[aria-current="page"] { color: var(--ink); background: var(--panel); box-shadow: inset 0 0 0 1px var(--line); }
.theme-toggle {
  font: 600 13px/1 var(--sans); color: var(--ink); background: var(--panel);
  border: 1px solid var(--line); border-radius: 999px; padding: 8px 14px; cursor: pointer;
}
.theme-toggle:hover { border-color: var(--accent); color: var(--link); }

/* ---- opening ---- */
.opening {
  max-width: 1240px; margin: 0 auto; padding: 56px 24px 40px;
  display: grid; grid-template-columns: minmax(0, 400px) minmax(0, 1fr); gap: 64px; align-items: center;
}
#hero {
  width: 100%; aspect-ratio: 1 / 1; border-radius: 24px; background: var(--stage);
  box-shadow: 0 0 0 1px var(--line); display: flex; align-items: center; justify-content: center; overflow: hidden;
}
#hero canvas { width: 100%; height: 100%; display: block; touch-action: none; }
#hero img { width: 62%; height: auto; }
.eyebrow { font: 500 12px/1.4 var(--mono); letter-spacing: .14em; text-transform: uppercase; color: var(--muted); margin: 0 0 18px; }
.opening-text h1 { font: 800 clamp(2rem, 4.4vw, 3rem)/1.05 var(--sans); letter-spacing: -0.035em; margin: 0 0 20px; }
.lead { font-size: 1.2rem; line-height: 1.55; color: var(--muted); margin: 0; max-width: 36ch; text-wrap: pretty; }
.lead strong { color: var(--ink); font-weight: 700; }
.cta { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 28px; }
.btn {
  display: inline-flex; align-items: center; gap: 8px; padding: 11px 18px; border-radius: 10px;
  font: 600 14px/1 var(--sans); text-decoration: none; border: 1px solid var(--line); background: var(--panel); color: var(--ink); white-space: nowrap;
}
.btn:hover { border-color: var(--accent); color: var(--link); }
.btn--primary { background: var(--accent); border-color: var(--accent); color: var(--on-accent); }
.btn--primary:hover { color: var(--on-accent); filter: brightness(.94); }
.hint { font: 400 12px/1.4 var(--mono); color: var(--muted); margin-top: 22px; letter-spacing: .04em; }

/* ---- layout: side nav + document ---- */
.layout { max-width: 1240px; margin: 0 auto; padding: 8px 24px 0; display: grid; grid-template-columns: 220px minmax(0, 1fr); gap: 56px; }
.sidenav { position: sticky; top: 88px; align-self: start; max-height: calc(100vh - 110px); overflow-y: auto; padding-bottom: 24px; }
.sidenav h2 { font: 500 11px/1.4 var(--mono); letter-spacing: .12em; text-transform: uppercase; color: var(--muted); margin: 0 0 10px; }
.sidenav ol { list-style: none; margin: 0; padding: 0; display: grid; gap: 2px; }
.sidenav a { display: block; padding: 6px 12px; border-radius: 8px; color: var(--muted); text-decoration: none; font: 500 14px/1.35 var(--sans); }
.sidenav a:hover { color: var(--ink); background: var(--panel); }
.sidenav a.is-active { color: var(--ink); background: var(--panel); box-shadow: inset 0 0 0 1px var(--line); }
.sidenav a.is-active::before { content: ""; display: inline-block; width: 8px; height: 8px; border-radius: 2px; background: var(--accent); margin-right: 8px; }

main.doc { min-width: 0; max-width: 780px; }
main.doc > p, main.doc > ul, main.doc > ol { max-width: 68ch; }
main.doc h1, main.doc h2, main.doc h3, main.doc h4 { font-family: var(--sans); line-height: 1.2; letter-spacing: -0.02em; text-wrap: balance; }
main.doc h1 { font-size: 2rem; margin: 0 0 .6em; }
main.doc h2 { font-size: 1.8rem; font-weight: 800; margin: 0 0 .7em; padding-top: 0; display: flex; align-items: center; gap: 14px; }
main.doc h2::before { content: ""; flex: none; width: 14px; height: 14px; border-radius: 3px; background: var(--accent); box-shadow: 18px 0 0 -4px var(--navy); margin-right: 10px; }
main.doc h3 { font-size: 1.2rem; font-weight: 700; margin: 2.1em 0 .45em; }
main.doc h4 { font-size: 1rem; font-weight: 700; }
main.doc hr { border: 0; height: 0; margin: 3.4em 0 2.6em; }
main.doc p, main.doc ul, main.doc ol { margin: 0 0 1.1em; }
main.doc li + li { margin-top: .3em; }
main.doc li::marker { color: var(--accent); }
main.doc strong { font-weight: 700; }
main.doc table {
  border-collapse: separate; border-spacing: 0; display: block; overflow-x: auto; max-width: 100%;
  font: 400 14px/1.5 var(--sans); margin: 1.6em 0; border: 1px solid var(--line); border-radius: 12px; background: var(--panel);
}
main.doc th, main.doc td { border-bottom: 1px solid var(--line); padding: 10px 14px; text-align: left; vertical-align: top; }
main.doc tbody tr:last-child td { border-bottom: 0; }
main.doc th { font: 500 11px/1.4 var(--mono); letter-spacing: .08em; text-transform: uppercase; color: var(--muted); background: var(--bg); white-space: nowrap; }
main.doc code { font-family: var(--mono); font-size: .86em; background: var(--inline-code); padding: .12em .4em; border-radius: 5px; }
main.doc pre { background: var(--code-bg); color: var(--code-ink); padding: 18px 20px; border-radius: 12px; overflow-x: auto; margin: 1.5em 0; line-height: 1.6; box-shadow: 0 0 0 1px var(--line); }
main.doc pre code { background: none; padding: 0; font-size: 13px; color: inherit; }
main.doc img { max-width: 100%; height: auto; }
main.doc details { border: 1px solid var(--line); background: var(--panel); border-radius: 12px; padding: 4px 18px; margin: 1.2em 0; }
main.doc details[open] { padding-bottom: 10px; }
main.doc summary { cursor: pointer; font: 700 15px/1.4 var(--sans); padding: 10px 0; }
main.doc summary:hover { color: var(--link); }
main.doc blockquote, main.doc aside.callout {
  margin: 1.6em 0; padding: 14px 18px 14px 50px; position: relative;
  background: var(--panel); border-radius: 12px; box-shadow: 0 0 0 1px var(--line); font-size: .96em;
}
main.doc blockquote::before, main.doc aside.callout::before {
  content: ""; position: absolute; left: 18px; top: 19px; width: 16px; height: 16px; border-radius: 4px; background: var(--accent);
}
main.doc aside.callout-warning::before { background: var(--coral); }
main.doc aside.callout-important::before { background: var(--navy); }
main.doc blockquote p, main.doc aside.callout p { margin: 0; }
main.doc figure.diagram {
  margin: 2em 0; padding: 0; border-radius: 16px; overflow: hidden; box-shadow: 0 0 0 1px var(--line); max-width: 100%;
}
main.doc figure.diagram img { display: block; width: 100%; height: auto; }
main.doc figure.diagram img.diagram--dark { display: none; }
html[data-theme="dark"] main.doc figure.diagram img.diagram--light { display: none; }
html[data-theme="dark"] main.doc figure.diagram img.diagram--dark { display: block; }
@media (prefers-color-scheme: dark) {
  html:not([data-theme="light"]) main.doc figure.diagram img.diagram--light { display: none; }
  html:not([data-theme="light"]) main.doc figure.diagram img.diagram--dark { display: block; }
}
pre.mermaid { background: var(--panel); color: var(--ink); text-align: center; }
.anchor-top { display: block; height: 0; }
main.doc p[align="right"] { text-align: right; font: 500 13px/1.4 var(--mono); margin: 0; }
main.doc p[align="right"] a { color: var(--muted); text-decoration: none; }
main.doc p[align="right"] a:hover { color: var(--link); }

footer.site {
  max-width: 1240px; margin: 72px auto 0; padding: 24px 24px 56px; border-top: 1px solid var(--line);
  display: flex; flex-wrap: wrap; justify-content: space-between; gap: 12px;
  font: 400 12px/1.5 var(--mono); letter-spacing: .04em; color: var(--muted);
}

@media (max-width: 1000px) {
  .layout { grid-template-columns: minmax(0, 1fr); gap: 0; }
  .sidenav { display: none; }
  main.doc { margin: 0 auto; }
}
@media (max-width: 760px) {
  .opening { grid-template-columns: 1fr; gap: 28px; padding-block: 28px; }
  #hero { max-width: 340px; margin: 0 auto; }
  .opening-text { text-align: center; }
  .lead { margin-inline: auto; }
  .cta { justify-content: center; }
  .opening-text h1 .lockup { height: 2.6rem; }
}
@media (prefers-reduced-motion: reduce) { html { scroll-behavior: auto; } }
"""

HERO_SCRIPT = '<script type="module" src="assets/hero.js"></script>'
MERMAID_SCRIPT = (
    '<script type="module">'
    'import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11.4.1/dist/mermaid.esm.min.mjs";'
    'mermaid.initialize({ startOnLoad: true, theme: "neutral" });'
    "</script>"
)
THEME_INIT = """<script>
(function () {
  try {
    var saved = localStorage.getItem('lab-theme');
    if (saved === 'light' || saved === 'dark') document.documentElement.setAttribute('data-theme', saved);
  } catch (e) {}
})();
</script>"""

PAGE_SCRIPT = """<script>
(function () {
  var root = document.documentElement, btn = document.getElementById('theme-toggle');
  function effective() {
    var explicit = root.getAttribute('data-theme');
    if (explicit) return explicit;
    return matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  }
  function label() {
    var dark = effective() === 'dark';
    btn.textContent = dark ? 'Light' : 'Dark';
    btn.setAttribute('aria-label', dark ? 'Switch to light theme' : 'Switch to dark theme');
  }
  label();
  btn.addEventListener('click', function () {
    var next = effective() === 'dark' ? 'light' : 'dark';
    root.setAttribute('data-theme', next);
    try { localStorage.setItem('lab-theme', next); } catch (e) {}
    label();
  });
  var links = [].slice.call(document.querySelectorAll('.sidenav a'));
  if (!links.length || !('IntersectionObserver' in window)) return;
  var byId = {};
  links.forEach(function (a) { byId[a.getAttribute('href').slice(1)] = a; });
  var heads = [].slice.call(document.querySelectorAll('main.doc h2[id]')).filter(function (h) { return byId[h.id]; });
  function activate() {
    var current = heads[0];
    heads.forEach(function (h) { if (h.getBoundingClientRect().top < 140) current = h; });
    links.forEach(function (a) { a.classList.toggle('is-active', current && byId[current.id] === a); });
  }
  addEventListener('scroll', activate, { passive: true });
  activate();
})();
</script>"""


def split_lead(body):
    """Take the first prose paragraph outside any blockquote to serve as the page's lead line."""
    quoted = [m.span() for m in re.finditer(r"<blockquote>.*?</blockquote>", body, flags=re.DOTALL)]
    for match in re.finditer(r"<p>(.*?)</p>", body, flags=re.DOTALL):
        if any(start <= match.start() < end for start, end in quoted):
            continue
        plain = re.sub(r"<[^>]+>", "", match.group(1)).strip()
        if len(plain) > 60:
            return match.group(1), body[: match.start()] + body[match.end():]
    return "", body


def figure(name, alt):
    alt = html.escape(alt, quote=True)
    return (
        '<figure class="diagram">'
        f'<img class="diagram--light" src="media/diagrams/{name}.svg" alt="{alt}" loading="lazy">'
        f'<img class="diagram--dark" src="media/diagrams/{name}-dark.svg" alt="" aria-hidden="true" loading="lazy">'
        "</figure>"
    )


def swap_diagrams(body):
    """Replace recognised Mermaid blocks with brand SVG figures."""

    def repl(match):
        for marker, figs in DIAGRAMS.items():
            if marker in match.group(1):
                return "".join(figure(n, a) for n, a in figs)
        return match.group(0)

    return re.sub(r'<pre class="mermaid">(.*?)</pre>', repl, body, flags=re.DOTALL)


def sidenav_html(body):
    """Side navigation built from the page's h2 headings."""
    items = []
    for m in re.finditer(r'<h2 id="([^"]+)">(.*?)</h2>', body, flags=re.DOTALL):
        text = re.sub(r"<[^>]+>", "", m.group(2)).strip()
        if m.group(1).startswith(("table-of-contents", "inhalts", "tabla-de", "table-des", "sumario", "目次", "目录")):
            continue
        items.append(f'<li><a href="#{m.group(1)}">{text}</a></li>')
    if not items:
        return ""
    return '<aside class="sidenav" aria-label="On this page"><h2>On this page</h2><ol>' + "".join(items) + "</ol></aside>"


def nav_html(current_out):
    links = []
    for _, out, label in PAGES:
        current = ' aria-current="page"' if out == current_out else ""
        links.append(f'<a href="{out}"{current}>{label}</a>')
    return '<nav aria-label="Documentation">{}</nav>'.format("".join(links))


def lockups(alt_light="lab-in-a-box"):
    return (
        f'<img class="lockup lockup--light" src="media/brand/lockup-horizontal-light.svg" alt="{alt_light}">'
        '<img class="lockup lockup--dark" src="media/brand/lockup-horizontal-dark.svg" alt="" aria-hidden="true">'
    )


def heading(title):
    """Page heading: the lockup logo in place of the 'lab-in-a-box' brand text, followed by any suffix."""
    brand = "lab-in-a-box"
    suffix = title[len(brand):] if title.startswith(brand) else ""
    return lockups() + html.escape(suffix)


def page(title, lead, body, current_out, mermaid):
    return "\n".join([
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width,initial-scale=1">',
        f"<title>{title}</title>",
        '<meta name="description" content="{}">'.format(
            html.escape(re.sub(r"<[^>]+>", "", lead).strip()[:160], quote=True)
        ),
        '<meta name="theme-color" content="#12a99d">',
        '<link rel="icon" href="media/brand/favicon.svg" type="image/svg+xml">',
        FONTS,
        IMPORT_MAP,
        f"<style>{STYLE}</style>",
        THEME_INIT,
        "</head>",
        "<body>",
        '<a id="top" class="anchor-top"></a>',
        '<div class="topbar-wrap"><header class="topbar">',
        f'<a href="index.html" aria-label="lab-in-a-box home">{lockups()}</a>',
        f'<div class="topbar-right">{nav_html(current_out)}',
        '<button type="button" class="theme-toggle" id="theme-toggle">Dark</button></div>',
        "</header></div>",
        '<section class="opening">',
        (
            '<div id="hero" role="img" aria-label="lab-in-a-box logo as a rotating 3D cube">'
            '<img src="media/brand/logo-3d-4f.svg" alt="lab-in-a-box logo"></div>'
        ),
        '<div class="opening-text">',
        '<p class="eyebrow">IT labs, deployed automatically</p>',
        f"<h1>{heading(title)}</h1>",
        f'<p class="lead">{lead}</p>',
        f'<div class="cta"><a class="btn btn--primary" href="{REPO_URL}">View on GitHub</a></div>',
        '<p class="hint">Drag the cube to rotate it.</p>',
        "</div>",
        "</section>",
        '<div class="layout">',
        sidenav_html(body),
        '<main class="doc">',
        body,
        "</main>",
        "</div>",
        f'<footer class="site"><span>lab in·a box</span><span>Generated from docs/src/ by docs/build_docs.py</span></footer>',
        PAGE_SCRIPT,
        HERO_SCRIPT,
        MERMAID_SCRIPT if mermaid else "",
        "</body>",
        "</html>",
        "",
    ])


def publish_media():
    """Copy the brand SVGs, diagram SVGs and the NUC photo under docs/media/: GitHub Pages serves docs/ as the site root."""
    for sub in ("brand", "diagrams"):
        target = DOCS / "media" / sub
        shutil.rmtree(target, ignore_errors=True)
        shutil.copytree(MEDIA / sub, target)
    shutil.copy2(MEDIA / "NUC.jpg", DOCS / "media" / "NUC.jpg")


def build():
    publish_media()
    for source, out, label in PAGES:
        body = (SOURCE / source).read_text(encoding="utf-8")
        lead, body = split_lead(body)
        body = swap_diagrams(body)
        title = "lab-in-a-box" if out == "index.html" else f"lab-in-a-box · {label}"
        page_html = page(title, lead, body, out, mermaid='class="mermaid"' in body)
        (DOCS / out).write_text(page_html, encoding="utf-8")
        print(f"wrote docs/{out}")


if __name__ == "__main__":
    if not SOURCE.is_dir():
        sys.exit(f"missing source directory: {SOURCE}")
    build()
